apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: slack-add-channel-
spec:
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: slack-token
          - name: channel-name
      steps:
        - - name: post-conversation
            template: http
            arguments:
              parameters:
                - name: url
                  value: "https://slack.com/api/conversations.create"
                - name: bearer-token
                  valueFrom:
                    secretKeyRef:
                      name: "{{inputs.parameters.slack-token}}"
                      key: token
                - name: channel-name
                  value: "{{inputs.parameters.channel-name}}"
    - name: http
      inputs:
        parameters:
          - name: url
          - name: bearer-token
          - name: channel-name
      http:
        timeoutSeconds: 20 
        url: "{{inputs.parameters.url}}"
        method: "POST"
        headers:
          - name: "Authorization"
            value: "Bearer {{inputs.parameters.bearer-token}}"
          - name: "Content-type"
            value: "application/json"
        body: '{"name":"{{inputs.parameters.channel-name}}"}'
