apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    argocdUrl: https://
  service.slack: |
    token: $slack-token
  defaultTriggers.slack: |
    - on-deleted
  trigger.on-deployed: |
    - send: [app-deployed]
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
  trigger.on-sync-status-unknown: |
    - when: app.status.sync.status == 'Unknown'
      send: [sync-is-unknown]
  trigger.on-app-health-degraded: |
    - when: app.status.health.status == 'Degraded'
      send: [app-health-degraded]
  trigger.on-app-sync-failed: |
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [app-sync-failed]
  template.app-deleted: |
    message: |
      Application {{.app.metadata.name}} has been deleted.
    slack:
      blocks: |
        [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "{{if eq .serviceType "slack"}}:bangbang:{{end}} Application {{.app.metadata.name}} has been deleted."
              },
              "accessory": {
                "type": "image",
                "image_url": "https://metakube.com/content/images/2023/02/argo-icon-color.png",
                "alt_text": "computer thumbnail"
              }
            }
        ]
  template.sync-is-unknown: |
    message: |
      {{if eq .serviceType "slack"}}:bangbang:{{end}} Application {{.app.metadata.name}} sync is 'Unknown'.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
    slack:
      blocks: |
        [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "{{if eq .serviceType "slack"}}:bangbang:{{end}} Application {{.app.metadata.name}} sync is :argo_unknown:'Unknown'.\n*Details*: <{{.context.argocdUrl}}/applications/{{.app.metadata.name}}|{{.app.metadata.name}}>"
              },
              "accessory": {
                "type": "image",
                "image_url": "https://metakube.com/content/images/2023/02/argo-icon-color.png",
                "alt_text": "computer thumbnail"
              }
            },
            {
              "type": "divider"
            }
            {{range $index, $c := .app.spec.sources}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Repository* {{trimSuffix ".git" ($c.repoURL | replace "https://github.com/infinit-il/" "") }}\n<{{ (trimAll ".git" $c.repoURL) }}/commit/{{ index $.app.status.sync.revisions $index }}|Commit>"
              },
              "accessory": {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "Link",
                  "emoji": true
                },
                "value": "click_me_123",
                "url": "{{trimSuffix ".git" $c.repoURL }}/tree/{{ $c.targetRevision }}/{{ $c.path }}",
                "action_id": "button-action"
              }
            },
            {
              "type": "divider"
            }
            {{end}}
          ]
  template.app-deployed: |
    message: |
      Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
    slack:
      blocks: |
        [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "{{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} is :argo_green_heart:Healthy and :green_vi:synced Succesfully.\n*Details*: <{{.context.argocdUrl}}/applications/{{.app.metadata.name}}|{{.app.metadata.name}}>"
              },
              "accessory": {
                "type": "image",
                "image_url": "https://metakube.com/content/images/2023/02/argo-icon-color.png",
                "alt_text": "computer thumbnail"
              }
            },
            {
              "type": "divider"
            }
            {{range $index, $c := .app.spec.sources}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Repository* {{trimSuffix ".git" ($c.repoURL | replace "https://github.com/infinit-il/" "") }}\n<{{ (trimAll ".git" $c.repoURL) }}/commit/{{ index $.app.status.sync.revisions $index }}|Commit>"
              },
              "accessory": {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "Link",
                  "emoji": true
                },
                "value": "click_me_123",
                "url": "{{trimSuffix ".git" $c.repoURL }}/tree/{{ $c.targetRevision }}/{{ $c.path }}",
                "action_id": "button-action"
              }
            },
            {
              "type": "divider"
            }
            {{end}}
          ]
  template.app-health-degraded: |
    message: |
      Application {{.app.metadata.name}} has degraded.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
    slack:
      blocks: |
        [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "{{if eq .serviceType "slack"}}:bangbang:{{end}} Application {{.app.metadata.name}} has :argo_broken_heart:degraded.\n*Details*: <{{.context.argocdUrl}}/applications/{{.app.metadata.name}}|{{.app.metadata.name}}>"
              },
              "accessory": {
                "type": "image",
                "image_url": "https://metakube.com/content/images/2023/02/argo-icon-color.png",
                "alt_text": "computer thumbnail"
              }
            },
            {
              "type": "divider"
            }
            {{range $index, $c := .app.spec.sources}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Repository* {{trimSuffix ".git" ($c.repoURL | replace "https://github.com/infinit-il/" "") }}\n<{{ (trimAll ".git" $c.repoURL) }}/commit/{{ index $.app.status.sync.revisions $index }}|Commit>"
              },
              "accessory": {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "Link",
                  "emoji": true
                },
                "value": "click_me_123",
                "url": "{{trimSuffix ".git" $c.repoURL }}/tree/{{ $c.targetRevision }}/{{ $c.path }}",
                "action_id": "button-action"
              }
            },
            {
              "type": "divider"
            }
            {{end}}
          ]
  template.app-sync-failed: |
    message: |
      The sync operation of application {{.app.metadata.name}} has failed
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
    slack:
      blocks: |
        [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "{{if eq .serviceType "slack"}}:bangbang:{{end}} The sync operation of application {{.app.metadata.name}} has failed at {{.app.status.operationState.finishedAt}}.\n*Details*: <{{.context.argocdUrl}}/applications/{{.app.metadata.name}}|{{.app.metadata.name}}>"
              },
              "accessory": {
                "type": "image",
                "image_url": "https://metakube.com/content/images/2023/02/argo-icon-color.png",
                "alt_text": "computer thumbnail"
              }
            },
            {
              "type": "divider"
            }
            {{range $index, $c := .app.spec.sources}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Repository* {{trimSuffix ".git" ($c.repoURL | replace "https://github.com/infinit-il/" "") }}\n<{{ (trimAll ".git" $c.repoURL) }}/commit/{{ index $.app.status.sync.revisions $index }}|Commit>"
              },
              "accessory": {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "Link",
                  "emoji": true
                },
                "value": "click_me_123",
                "url": "{{trimSuffix ".git" $c.repoURL }}/tree/{{ $c.targetRevision }}/{{ $c.path }}",
                "action_id": "button-action"
              }
            },
            {
              "type": "divider"
            }
            {{end}}
          ]


# You can’t call arbitrary Go methods, but you do have access to **sprig**, so I used this:
# {{ (trimAll ".git" .app.spec.source.repoURL) }}/-/commit/{{ .app.status.sync.revision }}

# useful links:
# https://app.slack.com/block-kit-builder/T04KHDLLP5K#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22Hey%20there%20%F0%9F%91%8B%20I'm%20TaskBot.%20I'm%20here%20to%20help%20you%20create%20and%20manage%20tasks%20in%20Slack.%5CnThere%20are%20two%20ways%20to%20quickly%20create%20tasks:%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*1%EF%B8%8F%E2%83%A3%20Use%20the%20%60/task%60%20command*.%20Type%20%60/task%60%20followed%20by%20a%20short%20description%20of%20your%20tasks%20and%20I'll%20ask%20for%20a%20due%20date%20(if%20applicable).%20Try%20it%20out%20by%20using%20the%20%60/task%60%20command%20in%20this%20channel.%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22*2%EF%B8%8F%E2%83%A3%20Use%20the%20_Create%20a%20Task_%20action.*%20If%20you%20want%20to%20create%20a%20task%20from%20a%20message,%20select%20%60Create%20a%20Task%60%20in%20a%20message's%20context%20menu.%20Try%20it%20out%20by%20selecting%20the%20_Create%20a%20Task_%20action%20for%20this%20message%20(shown%20below).%22%7D%7D,%7B%22type%22:%22image%22,%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22image1%22,%22emoji%22:true%7D,%22image_url%22:%22https://api.slack.com/img/blocks/bkb_template_images/onboardingComplex.jpg%22,%22alt_text%22:%22image1%22%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22%E2%9E%95%20To%20start%20tracking%20your%20team's%20tasks,%20*add%20me%20to%20a%20channel*%20and%20I'll%20introduce%20myself.%20I'm%20usually%20added%20to%20a%20team%20or%20project%20channel.%20Type%20%60/invite%20@TaskBot%60%20from%20the%20channel%20or%20pick%20a%20channel%20on%20the%20right.%22%7D,%22accessory%22:%7B%22type%22:%22conversations_select%22,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Select%20a%20channel...%22,%22emoji%22:true%7D%7D%7D,%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22context%22,%22elements%22:%5B%7B%22type%22:%22mrkdwn%22,%22text%22:%22%F0%9F%91%80%20View%20all%20tasks%20with%20%60/task%20list%60%5Cn%E2%9D%93Get%20help%20at%20any%20time%20with%20%60/task%20help%60%20or%20type%20*help*%20in%20a%20DM%20with%20me%22%7D%5D%7D%5D%7D
# https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_admin_notifications_template_notify/
# https://medium.com/@megaurav25/argocd-slack-notification-setup-a97ce5559ae0
